### ISSUE TITLE
Additional Records are parsed incorrect.

### ISSUE THREAD

**Issue by stefan-lemmens** [plasmapper/dns-client-labview#1]
In the vi "Parse Response Message" the authority and additional records are parsed incorrect because the offset starts from the beginning instead of continuing after the last answer. This can be solved by adding a shift register to the outer for-loop.

![image](https://user-images.githubusercontent.com/58171113/215443077-2b4d2608-0ac1-4c81-8aa3-3e3f56ed0aa5.png)

**Comment by plasmapper** [comment]
Fixed (c39e2f13aae6d6d6a01ee9874f8965521d76dbe7).
